trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type:       github
      ref:        main
      endpoint:   nivs-custom-devices
      name:       ni/niveristand-custom-device-build-tools

stages:
  # ---------------- Classic ----------------
  - template: azure-templates/stages.yml@niveristand-custom-device-build-tools
    parameters:
      stageName: Build_Classic
      lvVersionsToBuild:
        - version: '2024'
          bitness: '64bit'
        - version: '2025'
          bitness: '64bit'
        - version: '2026'
          bitness: '64bit'

      buildSteps:
        - projectLocation: 'Custom Device Classic\ProjectTemplate\Source\NI VeriStand\Custom Device\Consolidated Custom Device.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'My Computer'
          buildSpec: 'Configuration Source'

      releaseVersion: '26.0.0'
      buildOutputLocation: 'Custom Device Classic\ProjectTemplate'
      archiveLocation: '\\nirvana\Measurements\VeriStandAddons\niveristand-custom-device-wizard\Custom Device Classic'

      packages:
        - controlFileName: 'control'
          payloadMaps:
            - installLocation: 'ni-paths-LV$(lvVersion)DIR$(nipkgx64suffix)\ProjectTemplates'

  # ---------------- Express ----------------
  - template: azure-templates/stages.yml@niveristand-custom-device-build-tools
    parameters:
      stageName: Build_Express
      dependsOn: [ Build_Classic ]
      lvVersionsToBuild:
        - version: '2024'
          bitness: '64bit'
        - version: '2025'
          bitness: '64bit'
        - version: '2026'
          bitness: '64bit'

      buildSteps:
        - projectLocation: 'Custom Device Express\ProjectTemplate\Source\NI VeriStand\Custom Device Express\Custom Device\Custom Device Express.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'My Computer'
          buildSpec: 'Configuration Source'

      releaseVersion: '26.0.0'
      buildOutputLocation: 'Custom Device Express\ProjectTemplate'
      archiveLocation: '\\nirvana\Measurements\VeriStandAddons\niveristand-custom-device-wizard\Custom Device Express'

      packages:
        - controlFileName: 'control_custom_device_express'
          payloadMaps:
            - installLocation: 'ni-paths-LV$(lvVersion)DIR$(nipkgx64suffix)\ProjectTemplates'

