[archive]
build_output_dir = 'ProjectTemplate'
archive_location = '\\nirvana\Measurements\VeriStandAddons\niveristand-custom-device-wizard'

[projects.cd]
path = 'ProjectTemplate\Source\NI VeriStand\Custom Device\Null.lvproj'

[package]
type = 'nipkg'
payload_dir = 'ProjectTemplate'
install_destination = 'ni-paths-LV{labview_version}DIR{nipaths_64_bitness_suffix}\ProjectTemplates'

[notification]
type = 'teams'
